package com.google.idea.blaze.base.sync.reactive

import com.google.common.collect.ImmutableSet
import com.google.idea.blaze.base.command.BlazeCommand
import com.google.idea.blaze.base.command.BlazeCommandName
import com.google.idea.blaze.base.model.primitives.LanguageClass
import com.google.idea.blaze.base.model.primitives.WorkspaceRoot
import com.google.idea.blaze.base.sync.aspects.strategy.AspectStrategy
import com.google.idea.blaze.base.sync.aspects.strategy.AspectStrategy.OutputGroup
import com.google.idea.blaze.base.sync.data.BlazeProjectDataManager
import com.intellij.openapi.project.Project
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.io.IOException

private const val MANAGED_HEADER = "# Generated by the Bazel plugin; do not edit."

private val FALLBACK_LANGUAGES = setOf(LanguageClass.C)

@Throws(IOException::class)
private fun writeRcFile(path: Path, flags: List<String>) {
  Files.createDirectories(path.parent)

  Files.newOutputStream(path, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE).use { stream ->
    val builder = StringBuilder(MANAGED_HEADER)
    flags.forEach { builder.append("build $it\n") }
    stream.write(builder.toString().toByteArray())
  }
}

private fun getAspectFlags(project: Project, activeLanguages: Set<LanguageClass>): List<String> {
  return BlazeCommand.builder(BlazeCommandName.BUILD).apply {
    AspectStrategy.getInstance().addAspectAndOutputGroups(
      /* project = */ project,
      /* builder = */ this,
      /* outputGroups = */ ImmutableSet.of(OutputGroup.INFO),
      /* activeLanguages = */ activeLanguages,
    )
  }.build().cmdlineFlags().filter { it != "--" }
}

@Throws(IOException::class)
fun writeReactiveRcFileEnabled(path: Path, project: Project, bepFile: Path) {
  val activeLanguages = BlazeProjectDataManager.getInstance(project).blazeProjectData
    ?.workspaceLanguageSettings()
    ?.activeLanguages
    ?: FALLBACK_LANGUAGES

  val flags = buildList {
    addAll(getAspectFlags(project, activeLanguages))
    add("--build_event_binary_file=$bepFile")
    add("--nobuild_event_binary_file_path_conversion")
    add("--build_event_publish_all_actions")
  }

  writeRcFile(path, flags)
}

@Throws(IOException::class)
fun writeReactiveRcFileDisabled(path: Path) {
  writeRcFile(path, emptyList())
}

@Throws(IOException::class)
fun installReactiveRcImport(path: Path, project: Project) {
  val bazelrc = WorkspaceRoot.fromProject(project).directory().toPath().resolve(".bazelrc")

  // TODO: check if import already exists

  Files.newOutputStream(bazelrc, StandardOpenOption.CREATE, StandardOpenOption.APPEND).bufferedWriter().use { writer ->
    writer.appendLine()
    writer.appendLine(MANAGED_HEADER)
    writer.appendLine("try-import ${path.toAbsolutePath()}")
  }
}